import type { FirewallRule, Route, PppoeProfile, PppoeSecret } from "./types";

export const dummyInterfaces = [
    {
        id: "eth0",
        name: "Ethernet 0/0/1",
        description: "WAN Interface - Internet Connection",
        type: "ethernet",
        status: "up",
        adminStatus: "up",
        speed: 1000,
        duplex: "full",
        ip: "192.168.1.1",
        mask: "255.255.255.0",
        mac: "00:11:22:33:44:55",
        mtu: 1500,
        inOctets: 1234567890,
        outOctets: 987654321,
        inPackets: 8765432,
        outPackets: 6543210,
        inErrors: 0,
        outErrors: 0,
        inDrops: 12,
        outDrops: 5,
        utilization: 45.2,
        lastChange: "2024-01-15 08:30:45",
    },
    {
        id: "eth1",
        name: "Ethernet 0/0/2",
        description: "LAN Interface - Local Network",
        type: "ethernet",
        status: "up",
        adminStatus: "up",
        speed: 1000,
        duplex: "full",
        ip: "10.0.0.1",
        mask: "255.255.255.0",
        mac: "00:11:22:33:44:56",
        mtu: 1500,
        inOctets: 2345678901,
        outOctets: 1876543210,
        inPackets: 12345678,
        outPackets: 9876543,
        inErrors: 2,
        outErrors: 1,
        inDrops: 8,
        outDrops: 3,
        utilization: 23.7,
        lastChange: "2024-01-15 08:30:47",
    },
    {
        id: "wlan0",
        name: "WLAN 2.4GHz",
        description: "Wireless 2.4GHz - Guest Network",
        type: "wireless",
        status: "up",
        adminStatus: "up",
        speed: 300,
        duplex: "half",
        ip: "192.168.2.1",
        mask: "255.255.255.0",
        mac: "00:11:22:33:44:57",
        mtu: 1500,
        inOctets: 567890123,
        outOctets: 345678901,
        inPackets: 3456789,
        outPackets: 2345678,
        inErrors: 5,
        outErrors: 3,
        inDrops: 15,
        outDrops: 8,
        utilization: 12.4,
        lastChange: "2024-01-15 08:31:12",
    },
    {
        id: "wlan1",
        name: "WLAN 5GHz",
        description: "Wireless 5GHz - Main Network",
        type: "wireless",
        status: "down",
        adminStatus: "up",
        speed: 867,
        duplex: "half",
        ip: "192.168.5.1",
        mask: "255.255.255.0",
        mac: "00:11:22:33:44:58",
        mtu: 1500,
        inOctets: 890123456,
        outOctets: 567890123,
        inPackets: 5678901,
        outPackets: 4567890,
        inErrors: 1,
        outErrors: 0,
        inDrops: 4,
        outDrops: 2,
        utilization: 34.8,
        lastChange: "2024-01-15 08:31:15",
    },
];

export const dummyFirewallRules: FirewallRule[] = [
    {
        id: 1,
        chain: 'input',
        action: 'accept',
        protocol: 'tcp',
        srcAddress: '192.168.1.0/24',
        dstAddress: '0.0.0.0/0',
        dstPort: '80,443',
        comment: 'Allow web access from LAN',
        enabled: true,
        packets: 12345,
        bytes: 6543210,
    },
    {
        id: 2,
        chain: 'input',
        action: 'accept',
        protocol: 'udp',
        srcAddress: '0.0.0.0/0',
        dstAddress: '0.0.0.0/0',
        dstPort: '53',
        comment: 'Allow DNS queries',
        enabled: true,
        packets: 8765,
        bytes: 432109,
    },
    {
        id: 3,
        chain: 'forward',
        action: 'drop',
        protocol: 'all',
        srcAddress: '10.0.1.0/24',
        dstAddress: '0.0.0.0/0',
        dstPort: '',
        comment: 'Block guest network access to LAN',
        enabled: true,
        packets: 987,
        bytes: 54321,
    },
    {
        id: 4,
        chain: 'input',
        action: 'drop',
        protocol: 'tcp',
        srcAddress: '0.0.0.0/0',
        dstAddress: '0.0.0.0/0',
        dstPort: '22',
        comment: 'Drop external SSH',
        enabled: true,
        packets: 123,
        bytes: 6789,
    },
    {
        id: 5,
        chain: 'input',
        action: 'accept',
        protocol: 'icmp',
        srcAddress: '0.0.0.0/0',
        dstAddress: '0.0.0.0/0',
        dstPort: '',
        comment: 'Allow Ping',
        enabled: false,
        packets: 56,
        bytes: 2345,
    },
];

export const dummySecurityEvents = [
    {
        id: 'evt-1',
        timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
        severity: 'critical',
        eventType: 'DDoS Detected',
        sourceIp: '103.22.14.5',
        description: 'SYN flood attack detected on interface eth0. Packets dropped.',
    },
    {
        id: 'evt-2',
        timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        severity: 'warning',
        eventType: 'Login Failure',
        sourceIp: '202.55.18.2',
        description: 'Failed SSH login attempt for user `root`.',
    },
    {
        id: 'evt-3',
        timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        severity: 'info',
        eventType: 'Firewall Block',
        sourceIp: '192.168.1.102',
        description: 'Firewall rule #3 blocked outgoing connection to 123.45.67.89:1234.',
    },
    {
        id: 'evt-4',
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        severity: 'info',
        eventType: 'Login Success',
        sourceIp: '192.168.1.50',
        description: 'User `admin` successfully logged in via HTTPS.',
    },
    {
        id: 'evt-5',
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        severity: 'warning',
        eventType: 'Config Change',
        sourceIp: '192.168.1.50',
        description: 'User `admin` changed firewall rule #5.',
    },
    {
        id: 'evt-6',
        timestamp: new Date(Date.now() - 1000 * 60 * 72).toISOString(),
        severity: 'info',
        eventType: 'System',
        sourceIp: '127.0.0.1',
        description: 'System rebooted successfully.',
    },
];

export const dummyDdosThreats = [
    {
        id: 1,
        timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
        source: "203.0.113.45",
        type: "SYN Flood",
        severity: "Critical",
        confidence: 95.2,
        status: "Blocked",
        aiScore: 87.3,
    },
    {
        id: 2,
        timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
        source: "198.51.100.23",
        type: "UDP Flood",
        severity: "High",
        confidence: 89.7,
        status: "Monitoring",
        aiScore: 72.1,
    },
    {
        id: 3,
        timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
        source: "192.0.2.156",
        type: "Port Scan",
        severity: "Medium",
        confidence: 76.4,
        status: "Logged",
        aiScore: 58.9,
    },
];

export const dummyRoutes: Route[] = [
    {
        id: 1,
        destination: "0.0.0.0/0",
        gateway: "192.168.1.1",
        interface: "GigabitEthernet0/0/1",
        metric: 1,
        protocol: "Static",
        type: "Default",
        status: "active",
        age: "2d 5h",
    },
    {
        id: 2,
        destination: "192.168.1.0/24",
        gateway: "0.0.0.0",
        interface: "GigabitEthernet0/0/1",
        metric: 0,
        protocol: "Connected",
        type: "Direct",
        status: "active",
        age: "2d 5h",
    },
    {
        id: 3,
        destination: "192.168.100.0/24",
        gateway: "0.0.0.0",
        interface: "GigabitEthernet0/0/2",
        metric: 0,
        protocol: "Connected",
        type: "Direct",
        status: "active",
        age: "2d 5h",
    },
    {
        id: 4,
        destination: "10.0.0.0/8",
        gateway: "192.168.1.254",
        interface: "GigabitEthernet0/0/1",
        metric: 10,
        protocol: "OSPF",
        type: "Network",
        status: "active",
        age: "1d 12h",
    },
    {
        id: 5,
        destination: "172.16.0.0/16",
        gateway: "192.168.1.253",
        interface: "GigabitEthernet0/0/1",
        metric: 15,
        protocol: "RIP",
        type: "Network",
        status: "active",
        age: "0d 8h",
    },
    {
        id: 6,
        destination: "203.0.113.0/24",
        gateway: "192.168.1.1",
        interface: "GigabitEthernet0/0/1",
        metric: 5,
        protocol: "Static",
        type: "Network",
        status: "inactive",
        age: "0d 2h",
    },
];

export const dummyNotifications = [
    {
        id: 1,
        title: "Critical: DDoS Attack Mitigated",
        description: "A SYN flood attack from 103.22.14.5 was detected and blocked.",
        timestamp: new Date(Date.now() - 1000 * 60 * 2),
        read: false,
        type: "critical",
    },
    {
        id: 2,
        title: "New Firmware Available",
        description: "Version 8.190 is available for upgrade.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
        read: false,
        type: "info",
    },
    {
        id: 3,
        title: "High Memory Usage",
        description: "Memory usage has exceeded 90%.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
        read: true,
        type: "warning",
    },
    {
        id: 4,
        title: "User 'admin' logged in",
        description: "Successful login from IP 192.168.1.50.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
        read: true,
        type: "info",
    },
];

export const dummyPppoeActiveConnections = [
    {
        id: 1,
        username: "user001@huapau.net",
        service: "pppoe-service-1",
        ipAddress: "192.168.100.10",
        uptime: "2h 15m 30s",
        rxBytes: 1024000000,
        txBytes: 512000000,
        rxRate: "15.2 Mbps",
        txRate: "8.5 Mbps",
        sessionId: "0x1A2B3C4D",
        macAddress: "00:11:22:33:44:55",
        status: "active",
    },
    {
        id: 2,
        username: "admin@huapau.net",
        service: "pppoe-service-1",
        ipAddress: "192.168.100.11",
        uptime: "5h 42m 18s",
        rxBytes: 2048000000,
        txBytes: 1024000000,
        rxRate: "25.8 Mbps",
        txRate: "12.3 Mbps",
        sessionId: "0x2B3C4D5E",
        macAddress: "00:22:33:44:55:66",
        status: "active",
    },
    {
        id: 3,
        username: "guest@huapau.net",
        service: "pppoe-service-2",
        ipAddress: "192.168.100.12",
        uptime: "1h 8m 45s",
        rxBytes: 512000000,
        txBytes: 256000000,
        rxRate: "8.9 Mbps",
        txRate: "4.2 Mbps",
        sessionId: "0x3C4D5E6F",
        macAddress: "00:33:44:55:66:77",
        status: "active",
    },
];

export const dummyPppoeProfiles: PppoeProfile[] = [
    {
        id: 1,
        name: "Profile-5Mbps",
        localAddress: "192.168.88.1",
        remoteAddressPool: "pppoe-pool",
        rateLimit: "5M/5M",
        comment: "Standard 5 Mbps plan",
    },
    {
        id: 2,
        name: "Profile-10Mbps",
        localAddress: "192.168.88.1",
        remoteAddressPool: "pppoe-pool",
        rateLimit: "10M/10M",
        comment: "Premium 10 Mbps plan",
    },
    {
        id: 3,
        name: "Profile-Night",
        localAddress: "192.168.88.1",
        remoteAddressPool: "pppoe-pool",
        rateLimit: "20M/20M",
        comment: "Night-time booster plan",
    },
];

export const dummyPppoeSecrets: PppoeSecret[] = [
    {
        id: 1,
        username: "user001@huapau.net",
        service: "pppoe",
        profile: "Profile-5Mbps",
        lastLoggedIn: "2025-07-01 12:10:20",
        disabled: false,
    },
    {
        id: 2,
        username: "admin@huapau.net",
        service: "pppoe",
        profile: "Profile-10Mbps",
        lastLoggedIn: "2025-07-01 08:42:55",
        disabled: false,
    },
    {
        id: 3,
        username: "guest@huapau.net",
        service: "pppoe",
        profile: "Profile-5Mbps",
        lastLoggedIn: "2025-07-01 13:15:02",
        disabled: false,
    },
    {
        id: 4,
        username: "old_user@huapau.net",
        service: "pppoe",
        profile: "Profile-5Mbps",
        lastLoggedIn: "2025-06-15 10:00:00",
        disabled: true,
    },
];
